### ISSUE TITLE
Color for Text selection invisible on commit message

### ISSUE THREAD

**Issue by raul338** [m-thorsen/vscode-materia#1]
Hi! Thanks for the theme.

In Source Control, on the commit message area, if I select text, its indistinguishable from non-selected text. This do not happen in Search/Replace input

![Screenshot_20200617_122938](https://user-images.githubusercontent.com/7199046/84917907-51ab8680-b096-11ea-8061-57741baa5d06.png)

It happens with the three theme variants.
VS code: 1.46.0
KDE Theme: materia-kde 20200614, with breeze dark for gtk apps.
KDE plasma 5.19.1
KDE Frameworks 5.71.0

**Comment by m-thorsen** [comment]
Apparently there's some transparency blending shenanigans behind the scenes... 
https://github.com/Microsoft/vscode/issues/66098

The commit message input uses editor.selectionBackground instead of selection.background, and as such the selection highlight in the editor has also been updated.
